export const messageConfig = [
  {
    messageCode: 'AUTH_INVALID_TOKEN',
    messageText: 'Invalid token!'
  },
  {
    messageCode: 'AUTH_EMAIL_EXISTED',
    messageText: 'Email already existed!'
  },
  {
    messageCode: 'AUTH_INCORRECT_PASSWORD',
    messageText: `You've input wrong password!`
  },
  {
    messageCode: 'AUTH_EMAIL_NOT_FOUND',
    messageText: 'Email not existed!'
  },
  {
    messageCode: 'BRAND_SPOTLIGHT_MAXED',
    messageText: 'You can only add up to 10 brand spotlight!'
  },
];


// export enum ErrorCode {
//   // 400
//   BAD_REQUEST = 'BAD_REQUEST',
//   BAD_CONTENT = 'BAD_CONTENT',
//   KEY_EXPIRED = 'KEY_EXPIRED',
//   KEY_INVALID = 'KEY_INVALID',

//   PASSWORD_NOT_UPDATED = 'PASSWORD_NOT_UPDATED',
//   BRAND_WIDGET_IDS_INVALID = 'BRAND_WIDGET_IDS_INVALID',
//   BRAND_CANNOT_USE_OVER_ONE_TEMPLATE = 'BRAND_CANNOT_USE_OVER_ONE_TEMPLATE',

//   // 401
//   UNAUTHORIZED = 'UNAUTHORIZED',
//   AUTH_REQUIRED = 'AUTH_REQUIRED',
//   AUTH_ERROR = 'AUTH_ERROR',
//   SESSION_EXPIRED = 'SESSION_EXPIRED',
//   AUTH_INCORRECT_PASSWORD = 'AUTH_INCORRECT_PASSWORD',
//   AUTH_EMAIL_NOT_FOUND = 'AUTH_EMAIL_NOT_FOUND',

//   // 402
//   PAYMENT_REQUIRED = 'PAYMENT_REQUIRED',
//   DAILY_LIMIT_EXCEEDED = 'DAILY_LIMIT_EXCEEDED',
//   QUOTA_EXCEEDED = 'QUOTA_EXCEEDED',

//   // 403
//   FORBIDDEN = 'FORBIDDEN',

//   // 404
//   USER_NOT_FOUND = 'USER_NOT_FOUND',
//   USER_BRAND_NOT_FOUND = 'USER_BRAND_NOT_FOUND',
//   NOT_FOUND = 'NOT_FOUND',

//   // 405
//   METHOD_NOT_ALLOWED = 'METHOD_NOT_ALLOWED',
//   HTTP_METHOD_NOT_ALLOWED = 'HTTP_METHOD_NOT_ALLOWED',

//   // 408
//   REQUEST_TIMEOUT = 'REQUEST_TIMEOUT',

//   // 409
//   CONFLICT = 'CONFLICT',
//   DUPLICATE = 'DUPLICATE',
//   AUTH_EMAIL_EXISTED = 'AUTH_EMAIL_EXISTED',

//   // 429
//   RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
//   USER_RATE_LIMIT_EXCEEDED = 'USER_RATE_LIMIT_EXCEEDED',

//   // 500
//   INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',

//   // 501
//   NOT_IMPLEMENTED = 'NOT_IMPLEMENTED',
//   UNSUPPORTED_METHOD = 'UNSUPPORTED_METHOD',

//   // 503
//   SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
//   BACKEND_ERROR = 'BACKEND_ERROR',
//   NOT_READY = 'NOT_READY',
//   AUTH_INVALID_OTP = 'AUTH_INVALID_OTP',
//   AUTH_INVALID_TOKEN = 'AUTH_INVALID_TOKEN'
// }
