export enum Pages {
  LOGIN = 'login',
  DASHBOARD = 'dashboard',
  ERROR = 'error',
  AUTH = 'auth',
  ANALYTIC = 'analytic',
  USER_MANAGEMENT = 'user-management',
  BILLING_MANAGEMENT = 'billing-management',
  COMMUNITY_SPOTLIGHT = 'community-spotlight',
  BRAND_TEMPLATE = 'brand-template',
  CONTENT_MANAGEMENT = 'content-management',
  WIDGET_DESCRIPTION = 'widget-description',
  WIDGET_TIP = 'widget-tip',
  REPORTED_CONTENT = 'reported-content',
  PUSH_NOTIFICATION = 'push-notification',
  CUSTOMER_SUPPORT = 'customer-support',
  BACKGROUND_OPTIONS = 'background-options',

  MAINTENANCE = 'maintenance',
}
